version: '3.8'

services:
  # The Database
  mongo:
    image: mongo:latest
    container_name: helpdesk_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  # Web UI to view the Database
  mongo-express:
    image: mongo-express
    container_name: helpdesk_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
    depends_on:
      - mongo

  # RabbitMQ Service  ðŸ‘ˆ SAME INDENT LEVEL AS mongo & mongo-express
  rabbitmq:
    image: rabbitmq:3-management
    container_name: helpdesk_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Main AMQP port
      - "15672:15672" # Management UI
  
    # --- Backend Services ---
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - ticket-service

  auth-service:
    build: ./auth-service
    environment:
      - MONGO_URI=mongodb://admin:password123@mongo:27017/auth_db?authSource=admin
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo

  ticket-service:
    build: ./ticket-service
    environment:
      - MONGO_URI=mongodb://admin:password123@mongo:27017/ticket_db?authSource=admin
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  notification-service:
    build: ./notification-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq

  # --- Frontend ---
  client:
    build: ./client
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
volumes:
  mongo_data:
